### ISSUE TITLE
Xcode 9.3 building error

### ISSUE THREAD

**Issue by aplekhanov** [dreymonde/AppFolder#3]
Hello,
After update to Xcode 9.3 there are error now: 
`Ambiguous use of 'Caches'`

![screen shot 2018-03-30 at 10 17 48](https://user-images.githubusercontent.com/1385340/38128582-ca73ccb0-3403-11e8-9c37-0b0a156be13d.png)

**Comment by aplekhanov** [comment]
There's already pull request cover this issue - Fix ambiguous between variable and class

**Comment by dreymonde** [comment]
Thanks for reaching out! The problem is now solved in 8b313c87 (version 0.2.0)
